### ISSUE TITLE
java.lang.IllegalAccessException: Class org.apache.kafka.common.utils.Utils can not access a

### ISSUE THREAD

**Issue by wenxzhen** [jcustenborder/kafka-connect-cdc#3]
When I run the connector with Confluent 3.0.0, I met with the following error. What might be the problem?

I found the connect-api is in 0.10.2.0-cp1 instead of 0.10.2.0-SNAPSHOT? Would it be the root cause?

> [2017-06-24 03:13:35,525] ERROR Failed to add task oracle_cdc_validation-0:  (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:279)
> org.apache.kafka.connect.errors.ConnectException: Task class not found
>         at org.apache.kafka.connect.runtime.Worker.instantiateTask(Worker.java:367)
>         at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:325)
>         at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:277)
>         at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:308)
>         at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:165)
>         at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
> Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class com.github.jcustenborder.kafka.connect.cdc.logminer.OracleSourceTask
>         at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:316)
>         at org.apache.kafka.connect.runtime.Worker.instantiateTask(Worker.java:365)
>         ... 5 more
> Caused by: java.lang.IllegalAccessException: Class org.apache.kafka.common.utils.Utils can not access a member of class com.github.jcustenborder.kafka.connect.cdc.logminer.OracleSourceTask with modifiers ""
>         at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
>         at java.lang.Class.newInstance(Class.java:436)
>         at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
>         ... 6 more
> [2017-06-24 03:13:35,528] INFO Created connector oracle_cdc_validation (org.apache.kafka.connect.cli.ConnectStandalone:91)

**Comment by jcustenborder** [comment]
@wenxzhen 0.10.2.0 is Confluent Platform 3.2. The parent pom is using 0.10.2.0-cp1.

**Comment by wenxzhen** [comment]
@jcustenborder thank you very much.

What could be the problem as described above? Appreciated for any hints.

**Comment by wenxzhen** [comment]
Found the problem, I forgot to open the com.github.jcustenborder.kafka.connect.cdc.logminer.OracleSourceTask for public access.

**Comment by jcustenborder** [comment]
Sorry I didn't notice this. Glad you figured it out. I'm going to look at your branch this week.

**Comment by wenxzhen** [comment]
@jcustenborder Now I moved the repo to my organization here: https://github.com/c-datagroup/kafka-connect-cdc, appreciated for your review.
